name: Angular Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 23.3.0

      - name: Install dependencies
        run: npm clean-install

      - name: Run tests
        run: npm run test

      - name: Build Angular app
        run: npm run build:prod

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/tesla-app
          publish_branch: gh-pages
          cname: ''
          user_name: GitHub Actions
          user_email: mochulskyy.ruslan@gmail.com
